### ISSUE TITLE
Feature Request: negate search filter

### ISSUE THREAD

**Issue by B-u-z-z-T** [CJ-SPT/StashSearch#15]
Especially @fir would be nice to being able to negate that. So searching for @not-fir or @!fir or whatever filter-term. Not sure, if it would be needed or helpful for the other filters though.

**Comment by B-u-z-z-T** [comment]
Nevermind, just checked the code, if it might be easy to adapt, (easy enough, that even i could implement it) - but is already available. (just wasn't mentioned in the "Search Reference Sheet" - so that might be an idea, if somebody else is looking for that filter, too)

**Comment by CJ-SPT** [comment]
I'll try and remember to get that updated, keep forgetting about it
